### ISSUE TITLE
Performant question.

### ISSUE THREAD

**Issue by aq77103** [Elendan/RoR2-Mod-Menu#1]
Excuse me ，can you improve the performance of ESP，when i use it in quite a lot of monster scenes it well be very slow . When activating the ESP my fps decreases drastically :)

**Comment by BlowaXD** [comment]
Actually the menu is not even at a first release state, the code is pretty dirty and of course its performance could be improved.

We might reopen your issue if we get back into that project (probably at next ror2 update)
